server:
  compression:
     enabled: true
     mime-types: application/json,application/xml,text/html,text/xml,text/plain
  server-header: socialcast-connector

api:
  routingPrefix: /connectors/socialcast