package com.vmware.connectors.concur.domain;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.http.HttpMethod;

import java.util.LinkedHashMap;
import java.util.Map;

public class Action {

    @JsonProperty("label")
    private String label;

    @JsonProperty("url")
    private String url;

    @JsonProperty("type")
    private HttpMethod type;

    @JsonProperty("action_key")
    private String actionKey;

    @JsonProperty("request")
    private Map<String, String> request;

    public Action() {
        this.request = new LinkedHashMap<>();
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public HttpMethod getType() {
        return type;
    }

    public void setType(HttpMethod type) {
        this.type = type;
    }

    public String getActionKey() {
        return actionKey;
    }

    public void setActionKey(String actionKey) {
        this.actionKey = actionKey;
    }

    public Map<String, String> getRequest() {
        return request;
    }

    public void setRequest(Map<String, String> request) {
        this.request = request;
    }

    /**
     * Add a name/value pair to be sent with the request generated by the
     * CardAction. The key/value pairs are <i>not</i> stored in insertion order.
     *
     * @param key
     *            The name of the parameter to be added
     * @param value
     *            The value of the parameter to be added
     * @return this Builder instance, for method chaining
     */
    public void addRequestParam(String key, String value) {
        this.request.put(key, value);
    }

}
